### ISSUE TITLE
in videoscreen CommentsList not found

### ISSUE THREAD

**Issue by KingRizviAhmmed** [prateekmedia/flutube#1]
in videoscreen CommentsList not found. in videoscreen.dart there are many problem like  commentlist not found, getreplies not found

**Comment by prateekmedia** [comment]
<pre><font color="#5FD700">&gt;</font> <font color="#98C379">dart</font> analyze
Analyzing flutube...                   3.1s
No issues found!
</pre>

Everything's fine on my side. Can you post the output of your `dart analyze`?

Also have you ran `flutter pub get`.

**Comment by prateekmedia** [comment]
Closing due to lack of response.
