### ISSUE TITLE
Minor suggestion for release-assets

### ISSUE THREAD

**Issue by shuvashish76** [prateekmedia/flutube#27]
Add version code in the names of all packages.
It's hard to recognize versions if someone downloaded multiple releases of same type packages.
For reference check [KOReader](https://github.com/koreader/koreader/releases) release-assets.

Thankyou🙏🏿

**Comment by prateekmedia** [comment]
Done, You can see a demo here:
https://github.com/prateekmedia/flutube/releases/tag/continuous

**Comment by shuvashish76** [comment]
I see version code for apk files but not for other packages.
I meant for example if someone even download multiple AppImage versions, then that would be little problematic too.

Ignore this message,  if apks version code just for demonstration purpose only.
Thanks

**Comment by prateekmedia** [comment]
> 

It is only for development releases, When actual release is made it will use it.
