### ISSUE TITLE
request: direct download from url

### ISSUE THREAD

**Issue by sidmint** [prateekmedia/flutube#3]
a "direct download from url" sort of thing would be very time saving that would start download in pre set quality [if available, 3gpp should be always available], set from the settings, directly from the entered url. It's button can be placed where url is entered.

**Comment by sidmint** [comment]
I saw a feature to do this super easily in proproetary 4k video downloader app. By just clicking on 'add new' icon [and even in centre of the window] it grabs the link from the clipboard and starts downloading if video quality is already set.

**Comment by prateekmedia** [comment]
Yes, it will be implemented.

**Comment by prateekmedia** [comment]
Done in latest commit!
