### ISSUE TITLE
request: home screen and search access to be always present, clear all downloads option

### ISSUE THREAD

**Issue by sidmint** [prateekmedia/flutube#6]
home screen and search access should always be present to quickly search from anywhere and check downloads quickly. "Clear all" option in downloads would clean history easily.

**Comment by prateekmedia** [comment]
Fixed in https://github.com/prateekmedia/flutube/commit/83fdd24e02d24f13860476b7668600bcd88c0a43, Also search button is present mostly in all screens, and you can also press back to go to home.
