### ISSUE TITLE
Question: FreeTube

### ISSUE THREAD

**Issue by ovari** [prateekmedia/flutube#8]
Can you advise how your program is different to [FreeTube](https://freetubeapp.io/)?

Thank you

**Comment by prateekmedia** [comment]
FreeTube is something that currently is the 1-to-1 replacement for YouTube beside being open source.

But as you can see FreeTube is built on web technologies whereas FluTube is build using flutter. Also it is only for deskop whereas FluTube is Cross Platform.

FluTube at the current stage can be considered as in beta as this currently doesn't have everything working like video player, home screen / related videos recommendation etc which I would love if someone helps me adding that by creating a PR.
